name: e2fai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - intel
  - defaults
dependencies:
  - python=3.10
  - cmake
  - ninja
  - intel::mkl-include
  - intel::mkl-static
  - pytorch-cuda==12.1
  - lightning=2.3.0
  - absl-py
  - conda-forge::opencv=4.7.0
  - h5py=3.9.0
  - numba=0.60.0
  - imageio=2.34.2
  - hdf5plugin=4.1.3
  - numpy=1.26.4
  - pandas=1.5.2
  - scipy=1.13.1
  - pytorch==2.1.1
  - torchaudio==2.1.1
  - torchvision==0.16.1
  - matplotlib
  - wandb=0.16.5
  - scikit-image=0.24.0
  - filterpy==1.4.5
  - ffmpeg-python
  - plotly
  - omegaconf=2.3.0
